from typing import Any, Callable, TypeVar

def split_repr(self) -> str: ...
def normalize_repr(v) -> str: ...
def python3_repr(v) -> str: ...
def remove_defaults(d: dict, Callable[..., Any]) -> dict: ...
